export const SET_SINGER = 'SET_SINGER'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULLSCREEN = 'SET_FULLSCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCELIST = 'SET_SEQUENCELIST'

export const SET_MODE = 'SET_MODE'

export const SET_CURRENTINDEX = 'SET_CURRENTINDEX'

export const SET_DISC = 'SET_DISC'

export const SET_TOPLIST = 'SET_TOPLIST'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY'

export const SET_FAVORITE_LIST = 'SET_FAVORITE_LIST'
